### ISSUE TITLE
Repo owner

### ISSUE THREAD

**Issue by elahmo** [cwackerfuss/react-wordle#183]
I am wondering why this repository has moved to a new owner?

**Comment by cwackerfuss** [comment]
Hi @elahmo -- thanks for the question. The original owner (my partner) decided due to personal reasons that she would no longer be supporting the project. I wholeheartedly support her decision, and since I'm also a programmer (and helped a bit with the original implementation), told her I could continue supporting it. As you can see from the issues and pull request history, I (along with some other amazing members of the community) am working on continuing to improve the app and continue making this an awesome project.

**Comment by elahmo** [comment]
Gotcha, thanks for the transparency and a detailed response.
