### ISSUE TITLE
Dynamic Max Guess Size based on Word of the Day

### ISSUE THREAD

**Issue by KevinPiaskowski** [cwackerfuss/react-wordle#200]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a dynamic guess size that is pulled from the the word of the day.  It can still be up to the user/developer to define valid words and solutions but if the settings could update based on the word, that could be very interesting.

For example, if the word is "fox" the max guess size would be three but if the next day's word is "cattle" the max size would update to six based on the random word pull.

**Comment by cwackerfuss** [comment]
That's a neat idea I hadn't considered... I think the added complexity required to do this is probably something that fork maintainers would not find useful as a general feature since the original Wordle doesn't function like this.

This falls into the category of a feature I'd suggest building and maintaining in a fork.
