### ISSUE TITLE
Websocket failure to connect

### ISSUE THREAD

**Issue by yourjelly** [cwackerfuss/react-wordle#263]
https://github.com/facebook/create-react-app/issues/11779

In most cases adding

```
WDS_SOCKET_PORT=0
```
to `.env` file is enough to fix the bug and have it automatically map to the port you're hosting on.

If like me you're hosting behind a reverse proxy you may need to set `WDS_SOCKET_PORT=443`

**Comment by gheja** [comment]
I believe the WebSocket is only used when started in develpoment mode like this:
```bash
npm run start
```

When you do a regular build, it should not use WS:
```bash
npm run build
```

How are you building/starting it? If possible, could you share the commands you use?

**Comment by Xuereb** [comment]
Oh, I see. I'm kinda stumbling through this. So I'm running it from [this docker.](https://hub.docker.com/r/xavierh/cwackerfuss-react-wordle) Which does claim to be running the dev version. Which is fine because I'm actively tinkering with it.
```
FROM node:16.14.0-alpine3.14 AS node_modules
WORKDIR /app
COPY package-lock.json package.json ./
RUN npm install
COPY . .

FROM node_modules AS prod_builder
RUN npm run build

FROM nginx:1.20.2-alpine AS prod
COPY --from=prod_builder /app/build /usr/share/nginx/html
# Default HTTP port of Nginx.
EXPOSE 80

FROM node_modules AS dev
EXPOSE 3000
CMD npm run start
```
This is the docker file and I several pieces of what I didn't understand are now fitting together.

**Comment by modem7** [comment]
Seeing the same thing here on the latest Dockerfile build.
