### ISSUE TITLE
Shuffle the wordlist and store words that have been done already

### ISSUE THREAD

**Issue by eltaylor1104** [cwackerfuss/react-wordle#268]
**Is your feature request related to a problem? Please describe.**
Not a high-priority problem, just something that would be nice to see.

**Describe the solution you'd like**
Basically, as opposed to just going down the wordlist day-by-day, grab a random word from the wordlist, and insert it into a file so that it can be marked as "used" (or remove it from the wordlist). This solution would be ideal for an abundance of reasons, including making sure those that have to update the wordlist can still play enjoyably, making sure that when you "view source code" on the site it doesn't show the next x amount of days words in order, and this would also allow the wordlist to be neatly categorized alphabetically, which I personally would like to do so that I can see words that we may have before adding (I know I can control+f the wordlist, I just like things neat :) )

**Describe alternatives you've considered**
As mentioned before, the site could either store the word of the day and past words in a file, or remove from the wordlist.

**Additional context**
I hope this is feasible, I would love to see a system like this in place. Thank you all for the hard work that you have out into this, I love it!

**Comment by cwackerfuss** [comment]
Hey @eltaylor1104, thanks for the thoughtful issue!
One of the benefits of the original implementation is that everyone gets the same word every day, which promotes discussion and builds a strong community. We have mentioned before we don't want to introduce features like this to the core repo since most people want the classic experience, and those who don't can hopefully modify the source code how they'd like. Also, in the OG wordle you can definitely just view the wordlist via source as well, but that defeats the fun doesn't it?

For these reasons, this feature would be better as a fork. Closing this !
