### ISSUE TITLE
Way to see stats/ average guesses?

### ISSUE THREAD

**Issue by Kibris10** [cwackerfuss/react-wordle#283]
is there a way to see stats or average guesses to know what words caused trouble, or which ones were the easiest? or maybe also what words were guessed the most ?

**Comment by cwackerfuss** [comment]
Interesting - not in this core version though.. we only keep track of these stats, all just counts, not specific words: https://github.com/cwackerfuss/react-wordle/blob/main/src/lib/localStorage.ts#L20

This is not something we'd support in Reactle since it increases the complexity and scope of the local caching logic by quite a bit. Thank you for the suggestion!
