### ISSUE TITLE
Time change

### ISSUE THREAD

**Issue by krushil1** [cwackerfuss/react-wordle#355]
Is it possible if I can change the time to reset every 3 hours?

**Comment by gheja** [comment]
The guesses are calculated by taking the milliseconds elapsed since an epoch (2022-01-01 00:00:00 local time in this case) and dividing by 24 hours.

If you change the `msInDay` definition on this line, the word should change at every interval you specify:
https://github.com/cwackerfuss/react-wordle/blob/main/src/lib/words.ts#L81

**Comment by krushil1** [comment]
Got it! Thank you!
