### ISSUE TITLE
Feature request: send custom puzzles to friends

### ISSUE THREAD

**Issue by tmarkov** [cwackerfuss/react-wordle#96]
So, I imagine this having two parts:
1. A way to enter a word. It's checked against the word list (not guess list), and if it's present, an corresponding URL for that word is generated, like `https://web-site?index=masked_index`. Where `masked)index` is the index from word the wordlist, transformed to avoid accidental spoilers. For example, `masked_index = (517 * index) MOD 3947`.
2. When someone uses a custom URL, the word index is unmasked (same example, `index = (3237 * masked_index) MOD 3947`), and the corresponding word is used instead of the daily word.

**Comment by cwackerfuss** [comment]
This is an interesting idea! We've historically planned to keep this as close to the original implementation of the game as possible but if you'd like to implement this, you'd have @hannahcode and I's stamp of approval to merge.

If you do implement, in order to avoid having a "magic formula", I suggest using [btoa()](https://developer.mozilla.org/En/DOM/Window.btoa) and [atob()](https://developer.mozilla.org/en/DOM/window.atob) combined with [encodeURI()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) and [decodeURI()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI)

Example:
```js
const index = 12;
encodeURI(btoa(index)); // 'MTI='
decodeURI(atob('U29tZSB0ZXh0')); '12'
```

**Comment by tmarkov** [comment]
Yes, your suggestion on how to encode is certainly cleaner.
I've looked a bit about how to implement this, but there's one thing that confuses me. I see the word selection happens in [this function](https://github.com/hannahcode/word-guessing-game/blob/1f9a49aecef078d16ffa89ebe67aae4eb5552256/src/lib/words.ts#L15), but it also returns tomorrow's date. But I can't find what that's used for - and what to return there when the word's not based on date.

**Comment by cwackerfuss** [comment]
Yes, there is some refactoring to the `getWordOfDay` function that we need to do to better support suggestions like yours. I think it needs to be slightly more sophisticated and not simply evaluate on browser initialization. I'll take a look this weekend and see if I can refactor this. @tmarkov

**Comment by pietroppeter** [comment]
I would also love to have this available! A common scenario where I would see this used is after sharing your result, people usually are curious of one of your words used as guess.

A couple of remarks:
- it would be nice to be able to use any 5 letter word and not only those given by an an index (I guess it might be more complicated)
- whatever the method to encode the secret, it would be better if it includes a _salt_, a random seed added to the secret that would make it so that if you share the same word twice you (likely) get different urls

Of course both could be additional features to be added at a later stage.

**Comment by pietroppeter** [comment]
is this closed because it was implemented (cannot find merged PRs that refer to this) or because it would not be accepted anymore if implemented?
